# vim: set fdm=marker:
######################################################################
#
#   See COPYING file distributed along with the psignifit package for
#   the copyright and license terms
#
######################################################################

# The main Psignifit 3.x Makefile

#################### VARIABLE DEFINITIONS ################### {{{

DOCOUT=doc-html
PSIPP_SRC=src
.PHONEY: swignifit psipy

#}}}

#################### GROUPING FILES ################### {{{

PYTHONFILES=$(addprefix pypsignifit/, __init__.py psignidata.py psignierrors.py psigniplot.py psigobservers.py pygibbsit.py)
CFILES_LIB=$(addprefix src/, bootstrap.cc core.cc data.cc linalg.cc mclist.cc mcmc.cc optimizer.cc psychometric.cc rng.cc sigmoid.cc special.cc
HFILES_LIB=$(addprefix src/, bootstrap.h  core.h  data.h  errors.h linalg.h mclist.h mcmc.h optimizer.h prior.h psychometric.h rng.h sigmoid.h special.h psipp.h)
PSIPY_INTERFACE=$(addprefix psipy/, psipy.cc psipy_doc.h pytools.h)
SWIGNIFIT_INTERFACE=swignifit/swignifit.i
SWIGNIFIT_AUTOGENERATED=$(addprefix swignifit/, swignifit.py swignifit_wrap.cxx)
DOCFILES=$(addprefix doc-src/, API.rst index.rst TUTORIAL.rst *.png)

# }}}

#################### MAIN DEFINITIONS ################### {{{

build: python-build python-doc

install: python-install python-doc

clean: clean-python-doc clean-python-build psipp-clean

test: psipy-test swignifit-test psipp-test

python-install: psipy-install
	echo "Installing python extension"

python-build: psipy
	echo "Building python extension"

clean-python-build:
	echo "clean python build"
	-rm -rv build

python-doc: $(DOCFILES) $(PYTHONFILES) python-build
	echo "building sphinx documentation"
	PYTHONPATH=build/`ls -1 build | grep lib` sphinx-build doc-src $(DOCOUT)

clean-python-doc:
	echo "clean sphinx documentation"
	-rm -rv $(DOCOUT)

# }}}

#################### PSIPP COMMANDS ################### {{{

psipp:
	cd $(PSIPP_SRC) && $(MAKE)

psipp-clean:
	cd $(PSIPP_SRC) && $(MAKE) clean

psipp-test:
	cd $(PSIPP_SRC) && $(MAKE) test

# }}}

#################### PSIPY COMMANDS ################### {{{

psipy: $(PYTHONFILES) $(CFILES) $(HFILES) $(PSIPY_INTERFACE) setup_basic.py setup_psipy.py
	./setup_psipy.py build

psipy-install: psipy-build
	./setup_psipy.py install

psipy-test:
	-PYTHONPATH=build/`ls -1 build | grep lib` python tests/psipy_test.py

# }}}

#################### SWIGNIFIT COMMANDS ################### {{{

swignifit: $(PYTHONFILES) $(CFILES) $(HFILES) $(SWIGNIFIT_AUTOGENERATED) setup_basic.py setup_swignifit.py
	./setup_swignifit.py build

swignifit-install: swignifit-build
	./setup_swignifit.py install

$(SWIGNIFIT_AUTOGENERATED): $(SWIGNIFIT_INTERFACE)
	swig -c++ -python -v -Isrc -Ipsipy swignifit/swignifit.i

swignifit-clean:
	-rm -rf $(SWIGNIFIT_AUTOGENERATED)

swignifit-test: test-swignifit-wrap test-interface

test-swignifit-wrap:
	-PYTHONPATH=build/`ls -1 build | grep lib` python tests/swignifit_test.py

test-interface:
	-PYTHONPATH=build/`ls -1 build | grep lib` python tests/interface_test.py

# }}}
