Document: psignifit3
Title: Debian psignifit3 Manual
Author: <insert document author here>
Abstract: This manual describes what psignifit3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/psignifit3/psignifit3.sgml.gz

Format: postscript
Files: /usr/share/doc/psignifit3/psignifit3.ps.gz

Format: text
Files: /usr/share/doc/psignifit3/psignifit3.text.gz

Format: HTML
Index: /usr/share/doc/psignifit3/html/index.html
Files: /usr/share/doc/psignifit3/html/*.html
